language: node_js
node_js:
- 4
- 6
- 8
- 9
cache:
  directories:
  - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

jobs:
  include:
    - script:
        - npm run test
      node_js:
        - 4
        - 6
        - 8
    - script:
        - npm run test
        - npm run test:coverage
        - npm run test:coverage:upload
      node_js:
        -9
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
    - script: 
        - npm run docs
        - npm run deploydocs
      if: branch = master
